### PR TITLE
[RDY] Templated parser interfaces.

### PR DESCRIPTION
**Pull request by gfokkema**

### CODE REVIEW

**Comment by pvanagtmaal** [comment]
Wow, nice! Next reviewer may merge :+1:

**Comment by Unia** [comment]
Is it really necessary to use `Edge<String>` everywhere?

**Comment by Unia** [comment]
See 763ce9967dc0c374f879b5848dd33d8ab7844e1d for a commit that uses `Edge<?>`. The only `Edge<String>` remaining is the following:

```
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/services/GraphLoadService.java:            Iterator<Edge<String>> ep = new EdgeIterator(getEdgeFile());
```

**Comment by Unia** [comment]
Merging.

**Pull request merged**
