### PR TITLE
[RDY] Rename packages, interfaces and their implementations.

### PR DESCRIPTION
**Pull request by gfokkema**
Suffixed implementations with impl for clarity.
Do others agree that this creates a better overview?

### CODE REVIEW

**Comment by Unia** [comment]
We'll merge this once #35 and #41 are in.

**Comment by Balletie** [comment]
There's no HeaderParser interface, so I don't think it's important to make the distinction between interface and implementation in this case (since there's no interface to begin with).

**Comment by gfokkema** [comment]
I agree, but I do think we should let it stay in the package nl.tudelft.dnainator.parser.impl.
Updated PR to reflect this.

**Comment by Balletie** [comment]
Also consider moving the Graph and GraphBuilder implementations to an impl package, and leave Graph and GraphBuilder themselves in their current package.

**Comment by gfokkema** [comment]
Good catch, updated :).

**Comment by pvanagtmaal** [comment]
LGTM. Merging!

**Pull request merged**
