### PR TITLE
[RDY] Implement a skeleton UI to hook things into

### PR DESCRIPTION
**Pull request by Unia**
This PR implements a very basic UI: just a window with a toolbar and a graph. It is meant as an indication of what the product will look like and as a means to start developing the other components.

I still have to look into using Mockito to test Swing components, so consider this WIP until then.

### CODE REVIEW

**Comment by pvanagtmaal** [comment]
The size of the open icon seems to be too large on OSx. Also, a OS-dependent menu bar would be nice so the full size of the screen can be used for displaying the graph

**Comment by Unia** [comment]
You're saying you want to use a menubar instead of a toolbar? AFAIK, those are automatically moved to the panel on OS X. This is certainly doable, but it hides the options and requires more clicks to get what you want which hurts the workflow.

**Comment by pvanagtmaal** [comment]
The menubar would indeed be an option. It certainly would not hurt the workflow, as shortcuts can easily be created.

**Comment by gfokkema** [comment]
Refer to d9c32f8b55e9a59c7cff18b23b0c0194284db4c1 for an implementation that splits the Graph class into a DNAGraph, which holds our strains, and a DNAViewer, that manages and creates Views on these strains.

Renaming to DNAGraph and DNAViewer was necessary because of duplicate names, and well, we are graphing DNA, aren't we? ;p

**Comment by Unia** [comment]
Basic concensus seems to be that a menubar is indeed better, so I have updated the PR to use a menubar instead of the toolbar.

**Comment by Unia** [comment]
Cherrypicked @gfokkema's commit into the PR.

**Comment by gfokkema** [comment]
Sometimes, when the GUI starts, the graphstream Component stays blank.
You have to click inside the component for it to start rendering.

Also, sometimes the window can not get focus anymore, clicking on it's titlebar won't make it gain focus again (title stays gray instead of white).

**Comment by gfokkema** [comment]
This might be fixed by switching over to GraphStream 1.3.
Might also fix Skip's issue.

**Comment by Unia** [comment]
Cherrypicked @gfokkema's commit and rebased on upstream master.

**Comment by gfokkema** [comment]
Since mocking with Mockito does not yield a substantial increase in testing coverage, we decided not to test these UI classes for now. Signing off on PR.

**Pull request merged**
