### PR TITLE
[RDY] Add reset zoom and reset position functionality.

### PR DESCRIPTION
**Pull request by pvanagtmaal**
Added on hotkeys `<meta>+R` and `<meta>+T.`

### CODE REVIEW

**Comment by Unia** [comment]
D'oh, commented on the commit instead of the PR. Oh well, it's minor anyway.

Next reviewer may merge.

**Comment by pvanagtmaal** [comment]
@Unia Did it by hand as Scene Builder refused to work. Will check/fix.

**Comment by ohuang12** [comment]
Looks fine to me, all working like intended!

**Comment by gfokkema** [comment]
Fixed a bug in resetting the translation when zoomed in.

**Pull request merged**
