### PR TITLE
[RDY] Improve jump-to

### PR DESCRIPTION
**Pull request by Unia**
Supersedes #133, see the last commit of this PR to find out why.

### CODE REVIEW

**Comment by ohuang12** [comment]
Currently jumping to nodes seems to be broken again.
Furthermore something goes wrong with jumping to nodes as well.
Invalid input on the jump to annotations is not handled correctly.

**Comment by Unia** [comment]
^ All fixed :)

**Comment by gfokkema** [comment]
LGTM

**Comment by pvanagtmaal** [comment]
Merging.

**Pull request merged**
