### PR TITLE
[RDY] Use Maven modules to separate backend and frontend

### PR DESCRIPTION
**Pull request by Unia**
SIG's main point of improvement was to use Maven modules to explicitly separate different
components.

Sorry for the noise of moving imports around :expressionless:

### CODE REVIEW

**Comment by Balletie** [comment]
Maybe prefix "backend" and "frontend" with "dnainator-"?

**Comment by Balletie** [comment]
Why is there still a "src/" directory in the root directory?

**Comment by gfokkema** [comment]
Cherry-pick / squash https://github.com/unia/dnainator/compare/maven-modules...gfokkema:gerlof-maven-modules.

**Comment by gfokkema** [comment]
Blocking issue: checkstyle isn't working when using mvn site.
It seems like eclipse doesn't show checkstyle anymore either.

**Comment by Unia** [comment]
^ Fixed. Now AppBundle is failing, however.

**Comment by gfokkema** [comment]
Please see 74c63cb150bbec1bd1c42e1b695f402aa771db25 for reporting fix and for .sh files.

**Comment by Unia** [comment]
Everything seems to be working now :)

**Comment by pvanagtmaal** [comment]
LGTM :)

**Comment by gfokkema** [comment]
Tested everything:
- Checkstyle works in Eclipse
- Packaging jar works
- generating sites works

Merging.

**Pull request merged**
