### PR TITLE
[WIP] Calculate interestingness scores based on the phylogenetic tree.

### PR DESCRIPTION
**Pull request by Balletie**
Also define a range for "interestingness" scores to be between 0 and 1000.

Furthermore, the importance of individual scores are implemented using "importance modifiers", defined in the `ScoreIdentifier` interface.
Comes after #146

### CODE REVIEW

**Comment by Unia** [comment]
Looks nice! Perhaps we should merge `NewickLoadService` and `GraphLoadService`?

Also, it is not immediately clear to me how I would be using this in the UI to to the drawing. Could you explain that?

**Comment by Balletie** [comment]
1. Yes, perhaps we should. We should probably call it `FileLoadService` then. Maybe put it in a separate PR?
2. Within the UI, it's as simple as calling `getInterestingnessScore` on an `EnrichedSequenceNode`.

**Comment by Unia** [comment]
1. A separate PR is fine with me.
2. I'll get back to you on this as soon as this is merged.

**Comment by pvanagtmaal** [comment]
Done in #170.

**Pull request closed without merging**
