### PR TITLE
[RFC] Allow for arrow key scrolling

### PR DESCRIPTION
**Pull request by pvanagtmaal**
Scrolling using arrow keys. Speed increases while key is pressed, until a max speed is reached.

### CODE REVIEW

**Comment by gfokkema** [comment]
Looks good and works fine as well :).

**Comment by pvanagtmaal** [comment]
Correct, fixed it.

**Comment by gfokkema** [comment]
Looks good! Next person may merge.

**Comment by ohuang12** [comment]
Looks fine to me! Merging.

**Pull request merged**
